spring.application.name=inboox-ai-backend

# H2 Database
spring.datasource.url=jdbc:h2:mem:inbooxdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Load secrets
spring.config.import=optional:application-secrets.properties

# JWT Configuration
inbooxai.jwt.secret=${JWT_SECRET}
inbooxai.jwt.expiration=86400000

# Groq AI
groq.api.key=${GROQ_API_KEY}

